# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tracks', [dirname(__file__)])
        except ImportError:
            import _tracks
            return _tracks
        if fp is not None:
            try:
                _mod = imp.load_module('_tracks', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tracks = swig_import_helper()
    del swig_import_helper
else:
    import _tracks
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


import numpy as np
def read_tracks(file_name, measurements, labels):
  with open(file_name) as f:
    frames = int(next(f))
    tracks = int(next(f))
  measurements = measurements.astype(np.double)
  labels = labels.astype(np.int32)
  readTracks(file_name, measurements, labels)
  return measurements, labels

def write_tracks(file_name, measurements, labels):
  frames, tracks = measurements.shape
  measurements = measurements.astype(np.double)
  labels = labels.astype(np.int32)
  writeTracks(file_name, measurements, labels)



def readTracks(*args):
  return _tracks.readTracks(*args)
readTracks = _tracks.readTracks

def writeTracks(*args):
  return _tracks.writeTracks(*args)
writeTracks = _tracks.writeTracks
# This file is compatible with both classic and new-style classes.


